plans_dict = {'Tradovate': [{'plan_title': '25K Full Size Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/25k-Tradovate'},
                            {'plan_title': '50K Full Size Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/50k-Tradovate'},
                            {'plan_title': '75K Full Size Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/75k-Tradovate'},
                            {'plan_title': '100K Full Size Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/100k-Tradovate'},
                            {'plan_title': '150K Full Size Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/150k-Tradovate'},
                            {'plan_title': '250K Full Size Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/250k-Tradovate'},
                            {'plan_title': '300K Full Size Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/300k-Tradovate'},
                            {'plan_title': '100K Static Tradovate',
                             'plan_link': 'https://www.apextraderfunding.com/member/signup/100k-Static-Tradovate'}],
              'Rithmic': [{'plan_title': '25K Full Size Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/25k-Rithmic'},
                          {'plan_title': '50K Full Size Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/50k-Rithmic'},
                          {'plan_title': '75K Full Size Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/75k-Rithmic'},
                          {'plan_title': '100K Full Size Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/100k-Rithmic'},
                          {'plan_title': '150K Full Size Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/150k-Rithmic'},
                          {'plan_title': '250K Full Size Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/250k-Rithmic'},
                          {'plan_title': '300K Full Size Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/300k-Rithmic'},
                          {'plan_title': '100K Static Rithmic',
                           'plan_link': 'https://www.apextraderfunding.com/member/signup/100k-Static-Rithmic'}]}